on:
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: dotnet format --verify-no-changes ./PointOfSaleSystem/PointOfSaleSystem.sln
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: dotnet build -c Release ./PointOfSaleSystem/PointOfSaleSystem.sln
      - run: dotnet test ./PointOfSaleSystem/PointOfSaleSystem.sln